In [4]:
import numpy as np
#21
arr=np.array([[1,0],[0,1]])
arr=np.tile(arr,(4,4))
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [7]:
#22
arr=np.random.random((5,5))
print(arr)
narr=(arr-arr.min())/(arr.max()-arr.min())
print(narr)

[[0.18505885 0.23432625 0.85990028 0.22850171 0.68429077]
 [0.33928942 0.54587899 0.67480352 0.08591911 0.57152327]
 [0.10669506 0.02935268 0.91230227 0.46808688 0.41991852]
 [0.87979444 0.85460649 0.21878377 0.07213342 0.4939557 ]
 [0.7214622  0.60292798 0.69245767 0.94483483 0.57321612]]
[[0.17008105 0.22389685 0.90722424 0.21753459 0.71540236]
 [0.33855028 0.56421232 0.70503924 0.06178868 0.59222409]
 [0.08448267 0.         0.96446401 0.4792384  0.42662311]
 [0.92895504 0.90144173 0.20691948 0.04673028 0.50749544]
 [0.75600548 0.62652811 0.72432324 1.         0.59407324]]


In [10]:
#23
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [12]:
#24
a=np.random.random((5,3))
b=np.random.random((3,2))
print(a.dot(b))

[[0.83769024 0.96460883]
 [1.63704051 1.76759159]
 [1.29165842 1.34488398]
 [1.11391865 1.23687815]
 [0.60348739 0.69388346]]


In [15]:
#25
arr=np.arange(1,11)
arr[(arr>3) & (arr<8)]*=-1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


In [16]:
#26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [23]:
#27
Z=np.arange(np.random.random((5))
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

SyntaxError: invalid syntax (<ipython-input-23-2b90535468a4>, line 3)

In [31]:
#28#31
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
np.seterr(all="ignore")

nan
0
[-2.14748365e+09]


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [44]:
#30
a=([1,2,3,4])
b=([2,4,5,6])
print(np.intersect1d(a,b))

[2 4]


In [26]:
#29
arr=np.random.random((5))
print(arr)
print(np.around(arr))

[0.90988158 0.54449372 0.83269596 0.68916369 0.86088599]
[1. 1. 1. 1. 1.]


In [32]:
#32
print(np.sqrt(-1) == np.emath.sqrt(-1))


False


In [38]:
#33
today=np.datetime64('today','D')
print(today)
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
print(yesterday)
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print(tomorrow)


2020-03-04
2020-03-03
2020-03-05


In [42]:
#34
d=np.arange(np.datetime64('2016-07-01'),np.datetime64('2016-08-01'))
print(d)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [54]:
#36
z=np.random.random((10))*5
print(z)
print(np.round(z))
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[0.36051917 3.18753797 4.95470905 1.49894854 2.56349869 0.60177525
 4.36963527 3.26430544 4.87804204 1.18211935]
[0. 3. 5. 1. 3. 1. 4. 3. 5. 1.]
[0. 3. 4. 1. 2. 0. 4. 3. 4. 1.]
[0. 3. 4. 1. 2. 0. 4. 3. 4. 1.]
[0 3 4 1 2 0 4 3 4 1]
[0. 3. 4. 1. 2. 0. 4. 3. 4. 1.]


In [57]:
#37
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [69]:
#38
def generator():
    for i in range(10):
        yield i
arr=np.fromiter(generator(),dtype=int,count=-1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [75]:
#39
vect=np.linspace(0,1,12)
vect=vect[1:11]
print(vect)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [76]:
#40
sort(np.random.random((10)))

array([0.07887781, 0.26350984, 0.31788525, 0.3801898 , 0.50372403,
       0.50426497, 0.50630971, 0.50871469, 0.52649229, 0.77708498])

In [77]:
#41
arr=np.arange((10))
print(np.add.reduce(arr))

45


In [79]:
#42
a=np.random.random((5))
b=np.random.random((5))
#print(a==b)
print(np.array_equal(a,b))

False


In [81]:
#43
arr = np.zeros(10)
arr.flags.writeable = False
print(arr)
#arr[5]=1


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [84]:
#44
import numpy as np
arr= np.random.random((10,2))
x,y = arr[:,0], arr[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.70141472 1.13701281 0.81392773 0.9842471  0.89882956 0.35974769
 0.81294053 1.02305249 1.27610487 0.92312791]
[0.3390208  0.91523825 1.17737617 1.03751112 0.23087999 1.48544883
 0.58767947 0.53143897 0.81925338 0.6473226 ]


In [86]:
#45
arr=np.random.random((10))
print(arr)
arr[np.argmax(arr)]=0
print(arr)

[0.7511498  0.97510318 0.41668077 0.69348189 0.22569462 0.90099071
 0.50853476 0.4596599  0.50499824 0.10118132]
[0.7511498  0.         0.41668077 0.69348189 0.22569462 0.90099071
 0.50853476 0.4596599  0.50499824 0.10118132]


In [89]:
#46
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [97]:
#47
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
print(1.0/(x[:,np.newaxis]-y))

[[-0.25       -0.2        -0.16666667 -0.14285714]
 [-0.33333333 -0.25       -0.2        -0.16666667]
 [-0.5        -0.33333333 -0.25       -0.2       ]
 [-1.         -0.5        -0.33333333 -0.25      ]]


In [99]:
#47 way 2
x=np.array([1,2,3,4]).reshape((-1,1))
y=np.array([5,6,7,8])
print(1/(x-y))

[[-0.25       -0.2        -0.16666667 -0.14285714]
 [-0.33333333 -0.25       -0.2        -0.16666667]
 [-0.5        -0.33333333 -0.25       -0.2       ]
 [-1.         -0.5        -0.33333333 -0.25      ]]


In [107]:
#48
list=[np.int8, np.int32, np.int64]
for i in list:
   print(np.iinfo(i).min)
   print(np.iinfo(i).max)
list1=[np.float32, np.float64]
for i in list1:
   print(np.finfo(i).min)
   print(np.finfo(i).max)
   print(np.finfo(i).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [108]:
#49
arr=np.random.random((5,5))
print(arr)

[[0.89792166 0.8491503  0.32493288 0.58496134 0.05777691]
 [0.36551258 0.33911073 0.28252772 0.25775035 0.62285777]
 [0.54966785 0.2436911  0.58372255 0.54756699 0.92593724]
 [0.53245886 0.98745816 0.71318978 0.42031034 0.96986376]
 [0.34557708 0.82943976 0.66679854 0.19004004 0.53710944]]


In [115]:
#50
arr=np.random.uniform((3,5))
print(arr[(np.abs(arr-5)).argmin()])


4.257528984078991
